class Country():
    def __init__(self, name=[], capital=[], code='', tags=[]):
        self.name = name
        self.capital = capital
        self.code = code
        self.tags = tags

        every.append(self)


every = []

afghanistan = Country(
    name=['Afghanistan'],
    capital=['Kabul'],
    code='af',
    tags=['country', 'as', 'me'])
albania = Country(
    name=['Albania'],
    capital=['Tirana'],
    code='al',
    tags=['country', 'eu', 'balkan'])
algeria = Country(
    name=['Algeria'],
    capital=['Algiers'],
    code='dz',
    tags=['country', 'af'])
andorra = Country(
    name=['Andorra'],
    capital=['Andorra la Vella'],
    code='ad',
    tags=['country', 'eu'])
angola = Country(
    name=['Angola'],
    capital=['Luanda'],
    code='ao',
    tags=['country', 'af'])
antigua_and_barbuda = Country(
    name=['Antigua and Barbuda'],
    capital=['Saint Johns'],
    code='ag',
    tags=['country', 'na'])
argentina = Country(
    name=['Argentia'],
    capital=['Buenos Aires'],
    code='ar',
    tags=['country', 'sa'])
armenia = Country(
    name=['Armenia'],
    capital=['Yerevan'],
    code='am',
    tags=['country', 'as'])
australia = Country(
    name=['Australia'],
    capital=['Canberra'],
    code='au',
    tags=['country', 'au'])
austria = Country(
    name=['Austria'],
    capital=['Vienna'],
    code='at',
    tags=['country', 'eu'])
azerbaijan = Country(
    name=['Azerbaijan'],
    capital=['Baku'],
    code='az',
    tags=['country', 'as'])

bahamas = Country(
    name=['Bahamas'],
    capital=['Nassau'],
    code='bs',
    tags=['country', 'na'])
bahrain = Country(
    name=['Bahrain'],
    capital=['Manama'],
    code='bh',
    tags=['country', 'as', 'me'])
bangladesh = Country(
    name=['Bangladesh'],
    capital=['Dhaka'],
    code='bd',
    tags=['country', 'as'])
barbados = Country(
    name=['Barbados'],
    capital=['Bridgetown'],
    code='bb',
    tags=['country', 'na'])
belarus = Country(
    name=['Belarus'],
    capital=['Minsk'],
    code='by',
    tags=['country', 'eu'])
belgium = Country(
    name=['Belgium'],
    capital=['Brussels'],
    code='be',
    tags=['country', 'eu'])
belize = Country(
    name=['Belize'],
    capital=['Belmopan'],
    code='bz',
    tags=['country', 'na'])
benin = Country(
    name=['Benin'],
    capital=['Porto-Novo'],
    code='bj',
    tags=['country', 'af'])
bhutan = Country(
    name=['Bhutan'],
    capital=['Thumphu'],
    code='bt',
    tags=['country', 'as'])
bolivia = Country(
    name=['Bolivia'],
    capital=['La Paz', 'Sucre'],
    code='bo',
    tags=['country', 'sa'])
bih = Country(
    name=['Bosnia and Herzegovina'],
    capital=['Sarajevo'],
    code='ba',
    tags=['country', 'eu', 'balkan'])
botswana = Country(
    name=['Botswana'],
    capital=['Gaborone'],
    code='bw',
    tags=['country', 'af'])
brazil = Country(
    name=['Brazil'],
    capital=['Brasilia'],
    code='br',
    tags=['country', 'sa'])
brunei = Country(
    name=['Brunei'],
    capital=['Bandar Seri Begawan'],
    code='bn',
    tags=['country', 'as'])
bulgaria = Country(
    name=['Bulgaria'],
    capital=['Sofia'],
    code='bg',
    tags=['country', 'eu', 'balkan'])
burkina_faso = Country(
    name=['Burkina Faso'],
    capital=['Ouagadougou'],
    code='bf',
    tags=['country', 'af'])
burundi = Country(
    name=['Burundi'],
    capital=['Gitega'],
    code='bi',
    tags=['country', 'af'])

cambodia = Country(
    name=['cambodia'],
    capital=['Phnom Penh'],
    code='kh',
    tags=['country', 'as'])
cameroon = Country(
    name=['Cameroon'],
    capital=['Yaounde'],
    code='cm',
    tags=['country', 'af'])
canada = Country(
    name=['Canada'],
    capital=['Ottawa'],
    code='ca',
    tags=['country', 'na'])
cabo_verde = Country(
    name=['Cabo Verde', 'Cape Verde'],
    capital=['Praia'],
    code='cv',
    tags=['country', 'af'])
car = Country(
    name=['Central African Republic', 'CAR'],
    capital=['Bangui'],
    code='cf',
    tags=['country', 'af'])
chad = Country(
    name=['Chad'],
    capital=['N\'Djamena'],
    code='td',
    tags=['country', 'af'])
chile = Country(
    name=['Chile'],
    capital=['Santiago'],
    code='cl',
    tags=['country', 'sa'])
china = Country(
    name=['China'],
    capital=['Bejing'],
    code='cn',
    tags=['country', 'as'])
colombia = Country(
    name=['Colombia'],
    capital=['Bogota'],
    code='co',
    tags=['country', 'sa'])
comoros = Country(
    name=['Comoros'],
    capital=['Moroni'],
    code='km',
    tags=['country', 'af'])
drc = Country(
    name=['Democratic Republic of the Congo', 'DRC'],
    capital=['Kinshasa'],
    code='cd',
    tags=['country', 'af'])
roc = Country(
    name=['Republic of the Congo', 'ROC'],
    capital=['Brazzaville'],
    code='cf',
    tags=['country', 'af'])
costa_rica = Country(
    name=['Costa Rica'],
    capital=['San Jose'],
    code='cr',
    tags=['country', 'na'])
croatia = Country(
    name=['Croatia'],
    capital=['Zagreb'],
    code='hr',
    tags=['country', 'eu', 'balkan'])
cuba = Country(
    name=['Cuba'],
    capital=['Havana'],
    code='cu',
    tags=['country', 'na'])
cyprus = Country(
    name=['Cyprus'],
    capital=['Nicosia'],
    code='cy',
    tags=['country', 'eu', 'as'])
czechia = Country(
    name=['Czechia'],
    capital=['Prague'],
    code='cz',
    tags=['country', 'eu'])

denmark = Country(
    name=['Denmark'],
    capital=['Copenhagen'],
    code='dk',
    tags=['country', 'eu'])
djibouti = Country(
    name=['Djibouti'],
    capital=['Djibouti'],
    code='dj',
    tags=['country', 'af'])
dominica = Country(
    name=['Dominica'],
    capital=['Roseau'],
    code='dm',
    tags=['country', 'na'])
dominican_republic = Country(
    name=['Dominican Republic'],
    capital=['Santo Domingo'],
    code='do',
    tags=['country', 'na'])

east_timor = Country(
    name=['East Timor', 'Timore-Leste'],
    capital=['Dili'],
    code='tl',
    tags=['country', 'as'])
ecuador = Country(
    name=['Ecuador'],
    capital=['Quito'],
    code='ec',
    tags=['country', 'sa'])
egypt = Country(
    name=['Egypt'],
    capital=['Cairo'],
    code='eg',
    tags=['country', 'af'])
el_salvador = Country(
    name=['El Salvador'],
    capital=['San Salvador'],
    code='sv',
    tags=['country', 'na'])
equatorial_guinea = Country(
    name=['Equatorial Guinea'],
    capital=['Malabo'],
    code='gq',
    tags=['country', 'af'])
eritrea = Country(
    name=['Eritrea'],
    capital=['Asmara'],
    code='er',
    tags=['country', 'af'])
estonia = Country(
    name=['Estonia'],
    capital=['Tallinn'],
    code='ee',
    tags=['country', 'eu'])
ethiopia = Country(
    name=['Ethiopia'],
    capital=['Addis Ababa'],
    code='et',
    tags=['country', 'af'])
eswatini = Country(
    name=['Eswatini', 'Swaziland'],
    capital=['Mbabane', 'Lobamba'],
    code='sz',
    tags=['country', 'af'])

fiji = Country(
    name=['Fiji'],
    capital=['Suva'],
    code='fj',
    tags=['country', 'au'])
finland = Country(
    name=['Finland'],
    capital=['Helsinki'],
    code='fi',
    tags=['country', 'eu'])
france = Country(
    name=['France'],
    capital=['Paris'],
    code='fr',
    tags=['country', 'eu'])

gabon = Country(
    name=['Gabon'],
    capital=['Libreville'],
    code='ga',
    tags=['country', 'af'])
gambia = Country(
    name=['Gambia', 'The Gambia'],
    capital=['Banjul'],
    code='gm',
    tags=['country', 'af'])
georgia = Country(
    name=['Georgia'],
    capital=['Tblisi'],
    code='ge',
    tags=['country', 'as'])
germany = Country(
    name=['Germany'],
    capital=['Berlin'],
    code='de',
    tags=['country', 'eu'])
ghana = Country(
    name=['Ghana'],
    capital=['Accra'],
    code='gh',
    tags=['country', 'af'])
greece = Country(
    name=['Greece'],
    capital=['Athens'],
    code='gr',
    tags=['country', 'eu'])
grenada = Country(
    name=['Grenada'],
    capital=['St George\'s', 'Saint George\'s'],
    code='gd',
    tags=['country', 'na'])
guatemala = Country(
    name=['Guatemala'],
    capital=['Guatemala City'],
    code='gt',
    tags=['country', 'na'])
guinea = Country(
    name=['Guinea'],
    capital=['Conakry'],
    code='gn',
    tags=['country', 'af'])
guinea_bissau = Country(
    name=['Guinea-Bissau'],
    capital=['Bissau'],
    code='gw',
    tags=['country', 'af'])
guyana = Country(
    name=['Guyana'],
    capital=['Georgetown'],
    code='gy',
    tags=['country', 'sa'])

haiti = Country(
    name=['Haiti'],
    capital=['Port-au-Prince'],
    code='ht',
    tags=['country', 'na'])
honduras = Country(
    name=['Honduras'],
    capital=['Tegucigalpa'],
    code='hn',
    tags=['country', 'na'])
hungary = Country(
    name=['Hungary'],
    capital=['Budapest'],
    code='hu',
    tags=['country', 'eu'])

iceland = Country(
    name=['Iceland'],
    capital=['Reykjavik'],
    code='is',
    tags=['country', 'eu'])
india = Country(
    name=['India'],
    capital=['New Delhi'],
    code='in',
    tags=['country', 'as'])
indonesia = Country(
    name=['Indonesia'],
    capital=['Jakarta', 'Nusantara'],
    code='id',
    tags=['country', 'as'])
iran = Country(
    name=['Iran'],
    capital=['Tehran'],
    code='ir',
    tags=['country', 'as', 'me'])
iraq = Country(
    name=['Iraq'],
    capital=['Baghdad'],
    code='iq',
    tags=['country', 'as', 'me'])
ireland = Country(
    name=['Ireland'],
    capital=['Dublin'],
    code='ie',
    tags=['country', 'eu'])
israel = Country(
    name=['Israel'],
    capital=['Jerusalem'],
    code='il',
    tags=['country', 'as', 'me'])
italy = Country(
    name=['Italy'],
    capital=['Rome'],
    code='it',
    tags=['country', 'eu'])
ivory_coast = Country(
    name=['Ivory Coast', 'Cote d\'Ivoire'],
    capital=['Yamoussoukro', 'Abidjan'],
    code='ci',
    tags=['country', 'af'])

jamaica = Country(
    name=['Jamaica'],
    capital=['Kingston'],
    code='jm',
    tags=['country', 'na'])
japan = Country(
    name=['Japan'],
    capital=['Tokyo'],
    code='jp',
    tags=['country', 'as'])
jordan = Country(
    name=['Jordan'],
    capital=['Amman'],
    code='jo',
    tags=['country', 'as', 'me'])

kazakhstan = Country(
    name=['Kazakhstan'],
    capital=['Astana', 'Nur-Sultan'],
    code='kz',
    tags=['country', 'as'])
kenya = Country(
    name=['Kenya'],
    capital=['Nairobi'],
    code='ke',
    tags=['country', 'af'])
kiribati = Country(
    name=['Kiribati'],
    capital=['Tarawa Atoll'],
    code='ki',
    tags=['country', 'au'])
north_korea = Country(
    name=['North Korea'],
    capital=['Pyongyang'],
    code='kp',
    tags=['country', 'as'])
south_korea = Country(
    name=['South Korea'],
    capital=['Seoul'],
    code='kr',
    tags=['country', 'as'])
kosovo = Country(
    name=['Kosovo'],
    capital=['Pristina'],
    code='xk',
    tags=['country', 'eu', 'balkan'])
kuwait = Country(
    name=['Kuwait'],
    capital=['Kuwait'],
    code='kw',
    tags=['country', 'as', 'me'])
kyrgyzstan = Country(
    name=['Kyrgyzstan'],
    capital=['Bishkek'],
    code='kg',
    tags=['country', 'as'])

laos = Country(
    name=['Laos'],
    capital=['Vientiane'],
    code='la',
    tags=['country', 'as'])
latvia = Country(
    name=['Latvia'],
    capital=['Riga'],
    code='lv',
    tags=['country', 'eu'])
lebanon = Country(
    name=['Lebanon'],
    capital=['Beirut'],
    code='lb',
    tags=['country', 'as', 'me'])
lesotho = Country(
    name=['Lesotho'],
    capital=['Maseru'],
    code='ls',
    tags=['country', 'af'])
liberia = Country(
    name=['Liberia'],
    capital=['Monrovia'],
    code='lr',
    tags=['country', 'af'])
libya = Country(
    name=['Libya'],
    capital=['Tripoli'],
    code='ly',
    tags=['country', 'af'])
liechtenstein = Country(
    name=['Liechtenstein'],
    capital=['Vaduz'],
    code='li',
    tags=['country', 'eu'])
lithuania = Country(
    name=['Lithuania'],
    capital=['Vilnius'],
    code='lt',
    tags=['country', 'eu'])
luxembourg = Country(
    name=['Luxembourg'],
    capital=['Luxembourg'],
    code='lu',
    tags=['country', 'eu'])

madagascar = Country(
    name=['Madagascar'],
    capital=['Antananarivo'],
    code='mg',
    tags=['country', 'af'])
malawi = Country(
    name=['Malawi'],
    capital=['Lilongwe'],
    code='mw',
    tags=['country', 'af'])
malaysia = Country(
    name=['Malaysia'],
    capital=['Kuala Lumpur'],
    code='my',
    tags=['country', 'as'])
maldives = Country(
    name=['Maldives'],
    capital=['Male'],
    code='mv',
    tags=['country', 'as'])
mali = Country(
    name=['Mali'],
    capital=['Bamako'],
    code='ml',
    tags=['country', 'af'])
malta = Country(
    name=['Malta'],
    capital=['Valletta'],
    code='mt',
    tags=['country', 'eu'])
marshall_islands = Country(
    name=['Marshall Islands'],
    capital=['Majuro'],
    code='mh',
    tags=['country', 'au'])
mauritania = Country(
    name=['Mauritania'],
    capital=['Nouakchott'],
    code='mr',
    tags=['country', 'af'])
mauritius = Country(
    name=['Mauritius'],
    capital=['Port Louis'],
    code='mu',
    tags=['country', 'af'])
mexico = Country(
    name=['Mexico'],
    capital=['Mexico City'],
    code='mx',
    tags=['country', 'na'])
micronesia = Country(
    name=['Micronesia', 'Federated States of Micronesia'],
    capital=['Palikir'],
    code='fm',
    tags=['country', 'au'])
moldova = Country(
    name=['Moldova'],
    capital=['Chisinau'],
    code='md',
    tags=['country', 'eu'])
monaco = Country(
    name=['Monaco'],
    capital=['Monaco'],
    code='mc',
    tags=['country', 'eu'])
mongolia = Country(
    name=['Mongolia'],
    capital=['Ulaanbataar'],
    code='mn',
    tags=['country', 'as'])
montenegro = Country(
    name=['Montenegro'],
    capital=['Podgorica'],
    code='me',
    tags=['country', 'eu', 'balkan'])
moroco = Country(
    name=['Moroco'],
    capital=['Rabat'],
    code='ma',
    tags=['country', 'af'])
mozambique = Country(
    name=['Mozambique'],
    capital=['Maputo'],
    code='mz',
    tags=['country', 'af'])
myanmar = Country(
    name=['Mayanmar', 'Burma'],
    capital=['Naypyidaw', 'Nay Pyi Taw', 'Rangoon'],
    code='mm',
    tags=['country', 'as'])

namibia = Country(
    name=['Namibia'],
    capital=['Windhoek'],
    code='na',
    tags=['country', 'af'])
nauru = Country(
    name=['Nauru'],
    capital=['Yaren District', 'Yaren', 'No Official Capital'],
    code='nr',
    tags=['country', 'au'])
nepal = Country(
    name=['Nepal'],
    capital=['Kathmandu'],
    code='np',
    tags=['country', 'as'])
netherlands = Country(
    name=['Netherlands'],
    capital=['Amsterdam', 'The Hague'],
    code='nl',
    tags=['country', 'eu'])
new_zealand = Country(
    name=['New Zealand'],
    capital=['Wellington'],
    code='nz',
    tags=['country', 'au'])
nicaragua = Country(
    name=['Nicaragua'],
    capital=['Managua'],
    code='ni',
    tags=['country', 'na'])
niger = Country(
    name=['Niger'],
    capital=['Miamey'],
    code='ne',
    tags=['country', 'af'])
nigeria = Country(
    name=['Nigeria'],
    capital=['Abuja'],
    code='ng',
    tags=['country', 'af'])
north_macedonia = Country(
    name=['North Macedonia', 'Macedonia'],
    capital=['Skopje'],
    code='md',
    tags=['country', 'eu', 'balkan'])
norway = Country(
    name=['Norway'],
    capital=['Oslo'],
    code='no',
    tags=['country', 'eu'])

oman = Country(
    name=['Oman'],
    capital=['Muscat'],
    code='om',
    tags=['country', 'as', 'me'])

pakistan = Country(
    name=['Pakistan'],
    capital=['Islamabad'],
    code='pk',
    tags=['country', 'as'])
palau = Country(
    name=['Palau'],
    capital=['Melekeok'],
    code='pw',
    tags=['country', 'au'])
palestine = Country(
    name=['Palestine'],
    capital=['Jerusalem'],
    code='ps',
    tags=['country', 'as', 'me'])
panama = Country(
    name=['Panama'],
    capital=['Panama City'],
    code='pa',
    tags=['country', 'na'])
papua_new_guinea = Country(
    name=['Papua New Guinea'],
    capital=['Port Moresby'],
    code='pg',
    tags=['country', 'as'])
paraguay = Country(
    name=['Paraguay'],
    capital=['Asuncion'],
    code='py',
    tags=['country', 'sa'])
peru = Country(
    name=['Peru'],
    capital=['Lima'],
    code='pe',
    tags=['country', 'sa'])
philippines = Country(
    name=['Philippines'],
    capital=['Manila'],
    code='ph',
    tags=['country', 'as'])
poland = Country(
    name=['Poland'],
    capital=['Warsaw'],
    code='pl',
    tags=['country', 'eu'])
portugal = Country(
    name=['Portugal'],
    capital=['Lisbon'],
    code='pt',
    tags=['country', 'eu'])

qatar = Country(
    name=['Qatar'],
    capital=['Doha'],
    code='qa',
    tags=['country', 'as', 'me'])

romania = Country(
    name=['Romania'],
    capital=['Bucharest'],
    code='ro',
    tags=['country', 'eu', 'balkan'])
russia = Country(
    name=['Russia'],
    capital=['Moscow'],
    code='ru',
    tags=['country', 'eu', 'as'])
rwanda = Country(
    name=['Rwanda'],
    capital=['Kigali'],
    code='rw',
    tags=['country', 'af'])

st_kitts = Country(
    name=['St Kitts and Nevis', 'Saint Kitts and Nevis'],
    capital=['Basseterre'],
    code='kn',
    tags=['country', 'na'])
st_lucia = Country(
    name=['St Lucia', 'Saint Lucia'],
    capital=['Castries'],
    code='lc',
    tags=['country', 'na'])
st_vincent = Country(
    name=['St Vincent and the Grenadines', 'Saint Vincent and the Grenadines'],
    capital=['Kingstown'],
    code='vc',
    tags=['country', 'na'])
samoa = Country(
    name=['Samoa'],
    capital=['Apia'],
    code='ws',
    tags=['country', 'au'])
san_marino = Country(
    name=['San Marino'],
    capital=['San Marino'],
    code='sm',
    tags=['country', 'eu'])
sao_tome = Country(
    name=['Sao Tome', 'Sao Tome and Principe'],
    capital=['Sao Tome'],
    code='at',
    tags=['country', 'af'])
saudi_arabia = Country(
    name=['Saudi Arabia'],
    capital=['Riyadh'],
    code='sa',
    tags=['country', 'as', 'me'])
senegal = Country(
    name=['Senegal'],
    capital=['Dakar'],
    code='sn',
    tags=['country', 'as'])
serbia = Country(
    name=['Serbia'],
    capital=['Belgrade'],
    code='rs',
    tags=['country', 'eu', 'balkan'])
seychelles = Country(
    name=['Seychelles'],
    capital=['Victoria'],
    code='sc',
    tags=['country', 'af'])
sierra_leone = Country(
    name=['Sierra Leone'],
    capital=['Freetown'],
    code='sl',
    tags=['country', 'af'])
singapore = Country(
    name=['Singapore'],
    capital=['Singapore'],
    code='sg',
    tags=['country', 'as'])
slovakia = Country(
    name=['Slovakia'],
    capital=['Bratislava'],
    code='sk',
    tags=['country', 'eu'])
slovenia = Country(
    name=['Slovenia'],
    capital=['Ljubljana'],
    code='sl',
    tags=['country', 'eu'])
solomon_islands = Country(
    name=['Solomon Islands'],
    capital=['Honiara'],
    code='sb',
    tags=['country', 'au'])
somalia = Country(
    name=['Somalia'],
    capital=['Mogadishu'],
    code='so',
    tags=['country', 'af'])
south_africa = Country(
    name=['South Africa'],
    capital=['Pretoria', 'Cape Town', 'Bleomfontein'],
    code='za',
    tags=['country', 'af'])
spain = Country(
    name=['Spain'],
    capital=['Madrid'],
    code='es',
    tags=['country', 'eu'])
sri_lanka = Country(
    name=['Sri Lanka'],
    capital=['Colombo', 'Sri Jayewardenpura Kotte'],
    code='lk',
    tags=['country', 'as'])
sudan = Country(
    name=['Sudan'],
    capital=['Khartoum'],
    code='sd',
    tags=['country', 'af'])
south_sudan = Country(
    name=['South Sudan'],
    capital=['Juba'],
    code='ss',
    tags=['country', 'af'])
suriname = Country(
    name=['Suriname'],
    capital=['Paramaribo'],
    code='sr',
    tags=['country', 'sa'])
sweden = Country(
    name=['Sweden'],
    capital=['Stockholm'],
    code='se',
    tags=['country', 'eu'])
switzerland = Country(
    name=['Switzerland'],
    capital=['Bern'],
    code='ch',
    tags=['country', 'eu'])
syria = Country(
    name=['Syria'],
    capital=['Damascus'],
    code='sy',
    tags=['country', 'as', 'me'])

taiwan = Country(
    name=['Taiwan'],
    capital=['Taipei'],
    code='tw',
    tags=['country', 'as'])
tajikistan = Country(
    name=['Tajikistan'],
    capital=['Dushanbe'],
    code='tj',
    tags=['country', 'as'])
tanzania = Country(
    name=['Tanzania'],
    capital=['Dar es Salaam', 'Domdoma'],
    code='tz',
    tags=['country', 'af'])
thailand = Country(
    name=['Thailand'],
    capital=['Bangkok'],
    code='th',
    tags=['country', 'as'])
togo = Country(
    name=['Togo'],
    capital=['Lome'],
    code='tg',
    tags=['country', 'af'])
tonga = Country(
    name=['Tonga'],
    capital=['Nuku\'alofa'],
    code='to',
    tags=['country', 'au'])
trinidad = Country(
    name=['Trinidad and Tobago'],
    capital=['Port-of-Spain'],
    code='tt',
    tags=['country', 'na', 'sa'])
tunisia = Country(
    name=['Tunisia'],
    capital=['Tunis'],
    code='tn',
    tags=['country', 'af'])
turkey = Country(
    name=['Turkey', 'Turkiye'],
    capital=['Ankara'],
    code='tr',
    tags=['country', 'as', 'eu'])
turkmenistan = Country(
    name=['Turkmenistan'],
    capital=['Ashgabat'],
    code='tm',
    tags=['country', 'as'])
tuvalu = Country(
    name=['Tuvalu'],
    capital=['Funafuti'],
    code='tv',
    tags=['country', 'au'])

uganda = Country(
    name=['Uganada'],
    capital=['Kampala'],
    code='ug',
    tags=['country', 'af'])
ukraine = Country(
    name=['Ukraine'],
    capital=['Kyiv'],
    code='ua',
    tags=['country', 'eu'])
uae = Country(
    name=['United Arab Emerates', 'UAE'],
    capital=['Abu Dhabi'],
    code='ae',
    tags=['country', 'as', 'me'])
uk = Country(
    name=['United Kingdom', 'UK'],
    capital=['London'],
    code='gb',
    tags=['country', 'eu'])
usa = Country(
    name=['United States', 'United States of America', 'USA'],
    capital=['Washington DC', 'DC', 'Washington'],
    code='us',
    tags=['country', 'na'])
uruguay = Country(
    name=['Uruguay'],
    capital=['Montevideo'],
    code='uy',
    tags=['country', 'sa'])
uzbekistan = Country(
    name=['Uzbekistan'],
    capital=['Tashkent'],
    code='uz',
    tags=['country', 'as'])

vanuatu = Country(
    name=['Vanuatu'],
    capital=['Port-Vila'],
    code='vu',
    tags=['country', 'au'])
vatican = Country(
    name=['Vatican', 'Vatican City', 'Holy See'],
    capital=['Vatican', 'Vatican City', 'Holy See'],
    code='va',
    tags=['country', 'eu'])
venezuela = Country(
    name=['Venezuela'],
    capital=['Caracas'],
    code='ve',
    tags=['country', 'sa'])
vietnam = Country(
    name=['Vietnam'],
    capital=['Hanoi'],
    code='vn',
    tags=['country', 'as'])

yemen = Country(
    name=['Yemen'],
    capital=['Sanaa'],
    code='ye',
    tags=['country', 'as', 'me'])

zambia = Country(
    name=['Zambia'],
    capital=['Lusaka'],
    code='zm',
    tags=['country', 'af'])
zimbabwe = Country(
    name=['Zimbabwe'],
    capital=['Harare'],
    code='zw',
    tags=['country', 'af'])
